TIMING:
  TAP_MILLISEC: 210
  DOUBLE_TAP_MILLISEC: 0
  SYNTHETIC_KEYS_PAUSE_MILLISEC: 10

MAPPINGS:
  # caps as caps + esc
  - KEY: KEY_CAPSLOCK
    TAP: KEY_ESC
    HOLD: KEY_LEFTCTRL

  # lctrl as win
  - KEY: KEY_LEFTCTRL
    TAP: KEY_LEFTMETA
    HOLD: KEY_RIGHTMETA

  - KEY: KEY_LEFTALT
    TAP: KEY_BACKSPACE
    HOLD: KEY_LEFTALT

  - KEY: KEY_RIGHTALT
    TAP: KEY_ENTER
    HOLD: KEY_RIGHTALT
